# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Babbling from a child of the internet 

email: luke@lgdns.co.uk
description: > # this means to ignore newlines until "baseurl:"
  DevOps enthusiast automating with PowerShell.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.lukegriffith.co.uk" # the base hostname & protocol for your site
twitter_username: lukegriffith
github_username:  lukemgriffith

# Build settings
markdown: kramdown
